### ISSUE TITLE
Loop moved

### ISSUE THREAD

**Issue by marcosscriven** [marcosscriven/marcosscriven.github.io#2]
Just tidying up or removing small or old repos. I've thus move the loop repo code to here:

https://github.com/marcosscriven/marcosscriven.github.io/tree/master/loop

These were the people that starred it, so just letting you know in case you still use it:

@bytehigh
@imascarenhas
@polymorp
@f1driver
@chris-alexander
@ichilton
@Jbithell
@SharkSnap
@ghalfacree

**Comment by imascarenhas** [comment]
Thanks for letting us know Marcos.

Still using it here, albeit only on a Raspberry Pi to send data to
ThingSpeak.

**Comment by marcosscriven** [comment]
So sorry - I messed up here - my marcosscriven.github.io repo is in fact my GitHub pages repo, and I just noticed using this as a general repo sometimes causes me to get notifications that page generation has failed.

Thus I'm moving this BACK to the old repo at https://github.com/marcosscriven/loop
