### ISSUE TITLE
CGAL JS moved

### ISSUE THREAD

**Issue by marcosscriven** [marcosscriven/marcosscriven.github.io#3]
I've moved CGAL JS to my mono repo: https://github.com/marcosscriven/marcosscriven.github.io/tree/master/cgaljs

Notifying people who starred or forked

People who starred:

@kejace
@morriswinkler
@kaosat-dev
@connerk
@ashnur
@sylvainpion
@sherbondy
@abiank
@fromradio
@rulkens
@HuaiLeiTang
@ats777
@kgryte
@lrineau
@adarshk
@miketahani
@piggyzzw
@ejlo
@jhorikawa
@tojocky
@polkovnikov-ph
@sakrist
@alextsui05
@yiskang
@clothbot
@cinterloper
@arielm
@kaysonli
@freeuniverser
@ikarienator

People who forked:

@vaasan-ubi
@tomilov
@EinsteinsWorkshop
@leanprover
@miklobit
@tbfleming
@Rhombik
@kintel

**Comment by polkovnikov-ph** [comment]
@marcosscriven Thanks for the notification!

**Comment by lrineau** [comment]
@polkovnikov-ph Do you have a running demo of cgaljs?

**Comment by lrineau** [comment]
Ooops. I meant:

@marcosscriven  Do you have a running demo of cgaljs?

**Comment by marcosscriven** [comment]
@lrineau I've not actually touched it in a while - but unlike most of my one-off repos quite a few people had starred and forked this - you might be better of looking through that list of people who forked that I recorded above.

**Comment by marcosscriven** [comment]
So sorry - I messed up here - my marcosscriven.github.io repo is in fact my GitHub pages repo, and I just noticed using this as a general repo sometimes causes me to get notifications that page generation has failed.

Thus I'm moving this BACK to the old repo at https://github.com/marcosscriven/cgaljs
